apiVersion: v1
kind: Service
metadata:
  name: cozy-telemetry
  labels:
    app: cozy-telemetry
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cozy-telemetry
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
